version: "3.8"

services:
  rviz:
    depends_on:
      - master
    build:
      context: ../
      dockerfile: ./ros1/Dockerfile
    container_name: rviz_container
    privileged: true
    environment:
      - ROS_MASTER_URI=http://master:11311
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
      - XAUTHORITY=/tmp/.docker.xauth
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /tmp/.docker.xauth:/tmp/.docker.xauth:rw
    command: >
      /bin/bash -c "sleep 1 && \
                    source /ros_ws/devel/setup.bash && \
                    roslaunch rise_asset_description display.launch"
    # -----------------------------------------------------
    # For interactive. Try `docker compose exec rviz bash`.
    # stdin_open: true
    # tty: true
    # command: /bin/bash

  master:
    image: ros:noetic-ros-core
    container_name: ros_master_container
    command: ["roscore"]